from github import Github
from datetime import datetime, timezone
from config import GITHUB_TOKEN, TARGET_REPO

def format_issue_body(result):
    """Format analysis result as GitHub issue markdown."""
    scores = result["scores"]
    rag = result["rag"]
    analysis = result["analysis"]
    data = result["raw_data"]
    meta = data.get("meta", {})
    contributors = data.get("contributors", {})
    issues = data.get("issues", {})
    prs = data.get("pull_requests", {})

    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    body = f"""## Overall Status: {rag['overall']}

> Analyzed: [{result['repo']}](https://github.com/{result['repo']}) on {date}
> {meta.get('description', '')}

---

## Health Scorecard

| Dimension | Score | Status |
|---|---|---|
| Schedule | {scores['schedule']}/100 | {rag['schedule']} |
| Quality | {scores['quality']}/100 | {rag['quality']} |
| Team | {scores['team']}/100 | {rag['team']} |
| **Overall** | **{scores['overall']}/100** | **{rag['overall']}** |

---

## Executive Summary

{analysis.get('executive_summary', 'N/A')}

---

## Top Risks

"""
    for i, risk in enumerate(analysis.get('risks', []), 1):
        if isinstance(risk, dict):
            body += f"### {i}. {risk.get('title', '')}\n"
            body += f"{risk.get('description', '')}\n\n"
        else:
            body += f"- {risk}\n"

    body += "\n---\n\n## Recommendations\n\n"
    for i, rec in enumerate(analysis.get('recommendations', []), 1):
        if isinstance(rec, dict):
            body += f"### {i}. {rec.get('title', '')}\n"
            body += f"{rec.get('description', '')}\n\n"
        else:
            body += f"- {rec}\n"

    positive = analysis.get('positive_finding', '')
    if positive:
        body += f"\n---\n\n## ✅ Positive Finding\n\n{positive}\n"

    geo = result.get("geo", {})
    if geo and geo.get("friction_score") != "unknown":
        body += f"""
---

## 🌍 Geographic Distribution & Collaboration Friction

| Metric | Value |
|---|---|
| Timezone Spread | {geo.get('timezone_spread_hours', 'N/A')} hours |
| Friction Level | {geo.get('friction_label', 'N/A')} |
| Overlap Window | {geo.get('overlap_window_hours', 'N/A')} hours/day |
| PR SLA Recommendation | {geo.get('pr_sla_recommendation', 'N/A')} |
| Locations Resolved | {geo.get('resolved_count', 0)}/{geo.get('resolved_count', 0) + geo.get('unresolved_count', 0)} contributors |

### Resolved Locations
"""
    for c in geo.get("resolved", []):
        body += f"- **{c['login']}** — {c['location']} (UTC{'+' if c['utc_offset'] >= 0 else ''}{c['utc_offset']}), {c['percentage']}% contributions\n"

    if geo.get("unresolved"):
        body += "\n### Location Not Specified\n"
        for c in geo.get("unresolved", []):
            body += f"- **{c['login']}** — {c['location']}, {c['percentage']}% contributions\n"

    body += f"""
---

## Raw Metrics

| Metric | Value |
|---|---|
| Open Issues | {issues.get('total_open', 0)} |
| Avg Issue Age | {issues.get('avg_age_days', 0)} days |
| Critical Age Issues | {issues.get('critical_age', 0)} |
| Oldest Issue | {issues.get('oldest_days', 0)} days |
| Open PRs | {prs.get('total_open', 0)} |
| Stale PRs | {prs.get('stale_prs', 0)} |
| Contributors | {contributors.get('total_contributors', 0)} |
| Bus Factor | {contributors.get('bus_factor', 0)} |
| Days Since Last Push | {data.get('meta', {}).get('days_since_last_push', 0)} |

---

*Generated by Program Health Agent*
"""
    return body

def post_report(result):
    """Post health report as GitHub issue to target repo."""
    print(f"\n>>> Posting report to {TARGET_REPO}")

    try:
        g = Github(GITHUB_TOKEN)
        repo = g.get_repo(TARGET_REPO)

        date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        overall = result['rag']['overall']
        source = result['repo']

        title = f"{overall} Program Health Report — {source} — {date}"
        body = format_issue_body(result)

        issue = repo.create_issue(title=title, body=body)
        print(f"  ✓ Issue created: {issue.html_url}")
        return issue.html_url

    except Exception as e:
        print(f"  ✗ Failed to post report: {e}")
        return None